### ISSUE TITLE
Int32 vs Int64 for analog waveforms

### ISSUE THREAD

**Issue by paulmthompson** [paulmthompson/Intan.jl#11]
For SpikeSorting.jl and Intan.jl, I have used Int64s for all of the raw data that is streamed from the FPGA for consistency. The board only uses Int32s, so I wonder if making this change could lead to some performance benefits, particularly with writing the data.

**Comment by allenyin** [comment]
Each sample is only two bytes, signed or unsigned.
Plotting or saving two bytes per sample should be sufficient (int16 or uint16), and saves space.

**Comment by paulmthompson** [comment]
Word size converted to Int16 with https://github.com/paulmthompson/Intan.jl/commit/621e3f9ce46e05423b2e979137b2af8e0557a2b3
